{{- if empty ( lookup "v1" "Service" .Release.Namespace ( print .Values.coreDeploymentName "-svc" ) ) }}
  {{- print "Unable to find core deployment " .Values.coreDeploymentName | fail }}
{{- end }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-job"
  labels:
    app.kubernetes.io/name: my-helm
    app.kubernetes.io/component: core
    app.kubernetes.io/release: {{ .Release.Name }}
spec:
  schedule: {{.Values.jobSchedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: dependent-job
              image: {{ .Values.image }}:{{ .Values.imageTag }}
              imagePullPolicy: Always
              volumeMounts:
                {{- if .Values.volume}}
                - name: "{{ .Values.volume.name }}"
                  mountPath: /data
                {{- end }}
              command:
                - curl
                - {{ .Values.coreDeploymentName }}-svc.{{ .Release.Namespace }}.svc.cluster.local:8080
