apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app.kubernetes.io/name: my-helm
    app.kubernetes.io/component: core
    app.kubernetes.io/release: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
  selector:
    app.kubernetes.io/name: my-helm
    app.kubernetes.io/component: core
    app.kubernetes.io/release: {{ .Release.Name }}

